WHISPER_EXE = r"PATH_TO_WHISPER_EXE"
WHISPER_MODEL = r"PATH_TO_WHISPER_MODEL"

PIPER_EXE = r"PATH_TO_PIPER_EXE"
PIPER_MODEL = r"PATH_TO_PIPER_MODEL"

OLLAMA_MODEL = "qwen2.5-3b-instruct"

SHORTCUT_FOLDER = r"PATH_TO_SHORTCUTS"

EVERYTHING_EXE = r"PATH_TO_EVERYTHING"

AUDIO_FILE = "input.wav"
OUTPUT_WAV = "reply.wav"

SAMPLE_RATE = 16000
